version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: brinmalte-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: brinmalte
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - brinmalte-network

volumes:
  postgres-data:
    driver: local

networks:
  brinmalte-network:
    driver: bridge

